#Elementos de la pagina de registro
link_Reg = "link:REGISTER"
txt_firstName = "name:firstName"
txt_lastName = "name:lastName"
txt_phone = "name:phone"
txt_email = "name:userName"
txt_add = "name:address1"
txt_city = "name:city"
txt_state = "name:state"
txt_postCode = "name:postalCode"
drp_country = "name:country"
txt_userName = "name:email"
txt_Password = "name:password"
txt_conformedPassword = "name:confirmPassword"
btn_submit = "xpath://input[@name='submit']"